/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Deepspace.HangarToUI;
import Deepspace.ShieldToUI;
import Deepspace.WeaponToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author diagmatrix
 */
public class HangarToGUI extends javax.swing.JPanel {

    private WeaponToGUI weapon = new WeaponToGUI();
    private ShieldBoosterToGUI shield = new ShieldBoosterToGUI();
    
    /**
     * Creates new form HangarToGUI
     */
    public HangarToGUI() {
        initComponents();
        spaces_w.add(weapon);
        spaces_s.add(shield);
    }
    
    public void setHangarToGUI(HangarToUI h) {
        max_elements.setText(Integer.toString(h.getMaxElements()));
        ArrayList<WeaponToUI> weapons = h.getWeapons();
        ArrayList<ShieldToUI> shields = h.getShieldBoosters();
        spaces_w.removeAll();
        for (WeaponToUI w: weapons) {
            weapon.setWeaponToGUI(w);
            spaces_w.add(weapon);
        }
        spaces_s.removeAll();
        for (ShieldToUI s: shields) {
            shield.setShieldBoosterToGUI(s);
            spaces_s.add(shield);
        }
        repaint();
        revalidate();
    }
    
    public ArrayList<Integer> getSelectedWeapons() {
        ArrayList<Integer> aux = new ArrayList<>();
        int i = 0;
        for (Component w: spaces_w.getComponents()) {
            if (((CombatItems) w).isSelected())
                aux.add(i);
            i++;
        }
        return aux;
    }
    
    public ArrayList<Integer> getSelectedShields() {
        ArrayList<Integer> aux = new ArrayList<>();
        int i = 0;
        for (Component s: spaces_s.getComponents()) {
            if (((CombatItems) s).isSelected())
                aux.add(i);
            i++;
        }
        return aux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        max_elements = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spaces_w = new javax.swing.JPanel();
        spaces_s = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HANGAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Espacios:");

        max_elements.setText("max_elements");

        jScrollPane1.setViewportView(spaces_w);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(max_elements)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spaces_s, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(max_elements))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spaces_s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel max_elements;
    private javax.swing.JPanel spaces_s;
    private javax.swing.JPanel spaces_w;
    // End of variables declaration//GEN-END:variables
}
